apiVersion: v1
kind: Secret
metadata:
  name: webhook-secret
stringData:
  #https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line#creating-a-token
  token: 9d5c75ec916cd2665e01072907a7f19383fdcfe0
  secret: random-string-data
